# Generated by Django 4.0.3 on 2023-10-15 14:24

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    initial_data = [
        {
            "name": "Oil Filter",
            "description": "Removes contaminants from engine oil to ensure smooth engine performance.",
            "price": 8.99,
            "available_quantity": 30,
            "active": True,
        },
        {
            "name": "Brake Pads",
            "description": "Friction materials that provide stopping power for the vehicle.",
            "price": 25.99,
            "available_quantity": 20,
            "active": True,
        },
        {
            "name": "Radiator",
            "description": "Regulates the temperature of the engine to prevent overheating.",
            "price": 120.00,
            "available_quantity": 15,
            "active": True,
        },
        {
            "name": "Shock Absorber",
            "description": "Reduces the effects of traveling over rough surfaces, leading to improved ride quality.",
            "price": 45.99,
            "available_quantity": 25,
            "active": True,
        },
        {
            "name": "Carburetor",
            "description": "Mixes air and fuel for internal combustion engines in the proper ratio.",
            "price": 150.00,
            "available_quantity": 10,
            "active": True,
        },
        {
            "name": "Exhaust System",
            "description": "Channels exhaust gases out of the engine to reduce noise and improve performance.",
            "price": 200.00,
            "available_quantity": 12,
            "active": True,
        },
        {
            "name": "Starter Motor",
            "description": "Initiates the engine's operation by providing the initial rotation.",
            "price": 80.00,
            "available_quantity": 18,
            "active": True,
        },
        {
            "name": "Ignition Coil",
            "description": "Converts low voltage into high voltage for creating the electric spark in the spark plugs.",
            "price": 35.00,
            "available_quantity": 20,
            "active": True,
        },
        {
            "name": "Power Steering Pump",
            "description": "Provides hydraulic pressure to the power steering gear for easier steering.",
            "price": 120.00,
            "available_quantity": 15,
            "active": True,
        },
        {
            "name": "Timing Belt",
            "description": "Synchronizes the rotation of the crankshaft and the camshaft for engine operation.",
            "price": 40.00,
            "available_quantity": 22,
            "active": True,
        },
    ]

    for data in initial_data:
        Product.objects.create(**data)


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
